DELETE FROM obstacle;

INSERT INTO obstacle (
    name,
    river_id,
    river_km,
    latitude,
    longitude,
    obstacle_type,
    difficulty,
    requires_portage,
    source,
    verified,
    description
)
VALUES
    (
        'Wypływ z Jeziora Pietrzykowskiego Dużego',
        (SELECT id FROM river WHERE name='Brda'),
        228.5,
        NULL,
        NULL,
        'SHALLOW',
        'MODERATE',
        FALSE,
        'str. 9 Świeszyno–Trzyniec',
        NULL,
        'Płytka woda i bujna roślinność wodna utrudniają odnalezienie właściwego koryta rzeki.'
    ),
    (
        'Drewniany most',
        (SELECT id FROM river WHERE name='Brda'),
        228.0,
        NULL,
        NULL,
        'BRIDGE',
        'MODERATE',
        FALSE,
        'str. 9 Świeszyno–Trzyniec',
        NULL,
        'Kamieniste i płytkie dno. Przy niskim stanie wody konieczne jest przepychanie kajaka pod mostem.'
    ),
    (
        'Dawna zastawka',
        (SELECT id FROM river WHERE name='Brda'),
        223.5,
        NULL,
        NULL,
        'RAPIDS',
        'MODERATE',
        FALSE,
        'str. 11 Stara Brda Pilska–Żołna',
        NULL,
        'Bystrza i zniszczona zastawka. Przy niskim poziomie wody kajak trzeba holować wzdłuż brzegu.'
    ),
    (
        'Jaz w Starej Brdzie Pilskiej',
        (SELECT id FROM river WHERE name='Brda'),
        222.0,
        NULL,
        NULL,
        'WEIR',
        'HARD',
        TRUE,
        'str. 11 Stara Brda Pilska–Żołna',
        NULL,
        'Konieczność dobicia do prawego brzegu i przeniesienia kajaka przez most drogowo-wodny na odległość 70 metrów.'
    ),
    (
        'Kamienne bystrze w Nowej Brdzie',
        (SELECT id FROM river WHERE name='Brda'),
        208.0,
        NULL,
        NULL,
        'RAPIDS',
        'MODERATE',
        FALSE,
        'Nowa Brda–most Wojciecha',
        NULL,
        'Płytka woda z kamieniami ukryta między drewnianym drogowym a kolejowym mostem. Próby zatrzymania się w tym miejscu grożą wywrotką.'
    ),
    (
        'Przełom w rezerwacie Przytoń',
        (SELECT id FROM river WHERE name='Brda'),
        202.0,
        NULL,
        NULL,
        'FALLEN_TREE',
        'HARD',
        FALSE,
        'str. 13 Nowa Brda–most Wojciecha',
        NULL,
        'Odcinek pełen zwalonych potężnych buków i sosen, którym towarzyszą płytkie bystrza.'
    ),
    (
        'Uciążliwości koło Folbrychtu',
        (SELECT id FROM river WHERE name='Brda'),
        202.5,
        NULL,
        NULL,
        'FALLEN_TREE',
        'MODERATE',
        FALSE,
        'Nowa Brda–most Wojciecha',
        NULL,
        'Pod mostem przed rezerwatem woda mocno wiruje, kryjąc w nurcie zwalone drzewa i kamienie.'
    ),
    (
        'Jezioro Charzykowskie',
        (SELECT id FROM river WHERE name='Brda'),
        158.5,
        NULL,
        NULL,
        'OTHER',
        'MODERATE',
        FALSE,
        'str. 19 Konarzyny–Jezioro Charzykowskie',
        NULL,
        'Potężny, szeroki akwen, na którym łatwo o niebezpieczną falę wywołaną podmuchami wiatru.'
    ),
    (
        'Zapora hydroelektrowni w Mylofie',
        (SELECT id FROM river WHERE name='Brda'),
        129.0,
        NULL,
        NULL,
        'DAM',
        'HARD',
        TRUE,
        'str. 27 Męcikał–Mylof',
        NULL,
        'Uciążliwa, 200-metrowa przenoska omijająca zaporę. Leśnictwo udostępnia wózek do przewozu sprzętu.'
    ),
    (
        'Zwaliska drzew w Świcie',
        (SELECT id FROM river WHERE name='Brda'),
        78.5,
        NULL,
        NULL,
        'FALLEN_TREE',
        'DANGEROUS',
        FALSE,
        'str. 35 Rudzki Most–Piła Młyn',
        NULL,
        'Szybka woda niosąca bezpośrednio na kłody powalonych drzew, pomiędzy którymi trzeba precyzyjnie manewrować.'
    ),
    (
        'Przełom Uroczysko Piekło',
        (SELECT id FROM river WHERE name='Brda'),
        73.0,
        NULL,
        NULL,
        'RAPIDS',
        'HARD',
        FALSE,
        'str. 35 Rudzki Most–Piła Młyn',
        NULL,
        'Górski charakter Brdy przed miejscowością Piła Młyn z głazami i rwącym nurtem. W razie wywrotki rzeka łatwo zabiera sprzęt.'
    ),
    (
        'Zapora elektrowni Samociążek',
        (SELECT id FROM river WHERE name='Brda'),
        35.5,
        NULL,
        NULL,
        'DAM',
        'HARD',
        TRUE,
        'str. 41 Pieczyska–Samociążek',
        NULL,
        'Męcząca, licząca około 200 metrów przenoska wzdłuż płotu okalającego teren lokalnej hydroelektrowni.'
    ),
    (
        'Zapora elektrowni Tryszczyn',
        (SELECT id FROM river WHERE name='Brda'),
        29.0,
        NULL,
        NULL,
        'DAM',
        'HARD',
        TRUE,
        'str. 43 Samociążek–Janowo',
        NULL,
        'Transport kajaków z użyciem nieczynnych dawnych torów przeznaczonych do drewna na odległości około 80 metrów.'
    ),
    (
        'Śluza Staromiejska',
        (SELECT id FROM river WHERE name='Brda'),
        11.5,
        NULL,
        NULL,
        'LOCK',
        'EASY',
        FALSE,
        'str. 45 Bydgoszcz',
        NULL,
        'Zabytkowa konstrukcja w sercu Bydgoszczy pozwalająca na pokonanie spiętrzenia metodą bezpiecznego śluzowania.'
    ),
    (
        'Młyn w Kaszubie (Zbrzyca)',
        (SELECT id FROM river WHERE name='Zbrzyca'),
        24.2,
        NULL,
        NULL,
        'WEIR',
        'MODERATE',
        TRUE,
        'str. 53 Kaszuba–Widno',
        NULL,
        'Pozostałości starego założenia młyńskiego spiętrzającego wodę. Wymaga obejścia lewą stroną między dawnymi zabudowaniami.'
    ),
    (
        'Młyn Milachowo (Zbrzyca)',
        (SELECT id FROM river WHERE name='Zbrzyca'),
        21.0,
        NULL,
        NULL,
        'WEIR',
        'MODERATE',
        TRUE,
        'str. 53 Kaszuba–Widno',
        NULL,
        'Przenoska prawą stroną przy pozostałościach tartaku i zgliszczach starego spalonego młyna nad spiętrzonym stawem.'
    );