DELETE FROM obstacle
WHERE river_id = (SELECT id FROM river WHERE name='Wda');

INSERT INTO obstacle (
    name,
    river_id,
    river_km,
    latitude,
    longitude,
    obstacle_type,
    difficulty,
    requires_portage,
    source,
    verified,
    description
)
VALUES
    (
        'Zastawka Jeziora Lubiszewskiego',
        (SELECT id FROM river WHERE name='Wda'),
        181.5,
        NULL,
        NULL,
        'WEIR',
        'HARD',
        TRUE,
        'str. 9',
        NULL,
        'Lejkowaty wypływ zamknięty zastawką wymagający przeniesienia kajaka[cite: 13].'
    ),
    (
        'Staw młyński w Papierni',
        (SELECT id FROM river WHERE name='Wda'),
        181.0,
        NULL,
        NULL,
        'WEIR',
        'HARD',
        TRUE,
        'str. 9',
        NULL,
        'Zastawka zmuszająca do przenoski oraz pieszego holowania kajaka[cite: 13].'
    ),
    (
        'Staw młyński z zastawką w Lipuszu',
        (SELECT id FROM river WHERE name='Wda'),
        179.0,
        NULL,
        NULL,
        'WEIR',
        'HARD',
        TRUE,
        'str. 11 Papiernia—jezioro Schodno',
        NULL,
        'Zastawka młyńska wymagająca niewygodnego przeniesienia kajaków przez drogę[cite: 13].'
    ),
    (
        'Most betonowy Kościerzyna-Chojnice',
        (SELECT id FROM river WHERE name='Wda'),
        176.4,
        NULL,
        NULL,
        'BRIDGE',
        'MODERATE',
        FALSE,
        'str. 11 Papiernia—jezioro Schodno',
        NULL,
        'Przesmyk pod mostem z silnym nurtem kryjącym pale i kamienie[cite: 13].'
    ),
    (
        'Śluza za wypływem z jeziora w Borsku',
        (SELECT id FROM river WHERE name='Wda'),
        152.1,
        NULL,
        NULL,
        'LOCK',
        'HARD',
        TRUE,
        'str. 13 Jezioro Wdzydze—Borsk',
        NULL,
        'Infrastruktura techniczna wymagająca ostrożności i przenoski kajaka na cypel[cite: 13].'
    ),
    (
        'Most na trasie Wdzydze-Wiele',
        (SELECT id FROM river WHERE name='Wda'),
        151.9,
        NULL,
        NULL,
        'BRIDGE',
        'MODERATE',
        FALSE,
        'str. 13 Jezioro Wdzydze—Borsk',
        NULL,
        'Przeprawa w Borsku, pod którą woda tworzy kamieniste bystrze[cite: 13].'
    ),
    (
        'Przepust regulacyjny przed mostem drewnianym',
        (SELECT id FROM river WHERE name='Wda'),
        150.0,
        NULL,
        NULL,
        'WEIR',
        'HARD',
        TRUE,
        'str. 13 Jezioro Wdzydze—Borsk',
        NULL,
        'Zastawka wodna wymagająca przeniesienia sprzętu do starorzecza[cite: 13].'
    ),
    (
        'Most kolejowy na linii Czersk-Kościerzyna',
        (SELECT id FROM river WHERE name='Wda'),
        145.4,
        NULL,
        NULL,
        'BRIDGE',
        'EASY',
        FALSE,
        'Bąk-Wojtal',
        NULL,
        'Wiadukt kolejowy poniżej miejscowości Bąk[cite: 13].'
    ),
    (
        'Infrastruktura hydrotechniczna w Wojtalu',
        (SELECT id FROM river WHERE name='Wda'),
        139.5,
        NULL,
        NULL,
        'WEIR',
        'HARD',
        TRUE,
        'Bąk-Wojtal',
        NULL,
        'Zastawka, młyn i elektrownia wymagające 15-metrowej przenoski i trudnego wodowania[cite: 13].'
    ),
    (
        'Most kolejowy Kościerzyna-Bydgoszcz',
        (SELECT id FROM river WHERE name='Wda'),
        137.2,
        NULL,
        NULL,
        'BRIDGE',
        'MODERATE',
        FALSE,
        'Bąk-Wojtal',
        NULL,
        'Wiadukt z kamienistym bystrzem wymagającym ostrożności[cite: 13].'
    ),
    (
        'Mosty w Czarnej Wodzie',
        (SELECT id FROM river WHERE name='Wda'),
        130.0,
        NULL,
        NULL,
        'BRIDGE',
        'MODERATE',
        FALSE,
        'Wieck-Jastrzębie',
        NULL,
        'Mosty kolejowy i drogowy, pod którymi nurt tworzy silne bystrze z kamieniami[cite: 13].'
    ),
    (
        'Most w Zimnych Zdrojach',
        (SELECT id FROM river WHERE name='Wda'),
        123.0,
        NULL,
        NULL,
        'BRIDGE',
        'EASY',
        FALSE,
        'Zimne Zdroje—Czarne',
        NULL,
        'Most drogowy bez trudności technicznych[cite: 13].'
    ),
    (
        'Próg za mostem w Czubku',
        (SELECT id FROM river WHERE name='Wda'),
        117.0,
        NULL,
        NULL,
        'WEIR',
        'EASY',
        FALSE,
        'Zimne Zdroje—Czarne',
        NULL,
        'Bezpieczny i łatwy do przepłynięcia próg rzeczny[cite: 13].'
    ),
    (
        'Pozostałości dawnego mostu',
        (SELECT id FROM river WHERE name='Wda'),
        94.0,
        NULL,
        NULL,
        'OTHER',
        'DANGEROUS',
        FALSE,
        'str. 25 Wda–Smolniki',
        NULL,
        'Niebezpieczne pale w nurcie rzeki[cite: 13].'
    ),
    (
        'Most kolejowy Chojnice–Skórcz',
        (SELECT id FROM river WHERE name='Wda'),
        93.6,
        NULL,
        NULL,
        'BRIDGE',
        'MODERATE',
        FALSE,
        'str. 25 Wda–Smolniki',
        NULL,
        'Bystrze i kamienie wymagające zachowania ostrożności[cite: 13].'
    ),
    (
        'Elektrownia wodna we Wdeckim Młynie',
        (SELECT id FROM river WHERE name='Wda'),
        85.0,
        NULL,
        NULL,
        'DAM',
        'HARD',
        TRUE,
        'str. 25 Wda–Smolniki',
        NULL,
        'Obowiązkowa przenoska prawą stroną z trudnym wodowaniem[cite: 13].'
    ),
    (
        'Elektrownia Żur',
        (SELECT id FROM river WHERE name='Wda'),
        34.5,
        NULL,
        NULL,
        'DAM',
        'HARD',
        TRUE,
        'str. 33',
        NULL,
        'Przenoska prawą stroną na odcinku około 150 m[cite: 13].'
    ),
    (
        'Elektrownia Gródek',
        (SELECT id FROM river WHERE name='Wda'),
        23.2,
        NULL,
        NULL,
        'DAM',
        'HARD',
        TRUE,
        'str. 33',
        NULL,
        'Przenoska lewą stroną o długości około 200 m przy zaporze[cite: 13].'
    ),
    (
        'Zastawy młynów w Świeciu Przechowie',
        (SELECT id FROM river WHERE name='Wda'),
        6.3,
        NULL,
        NULL,
        'WEIR',
        'HARD',
        TRUE,
        'str. 37',
        NULL,
        'Obowiązkowa przenoska lewą stroną przez ruchliwą drogę[cite: 13].'
    );